AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create an EC2 instance

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-03972092c42e8c0ca'  # Replace with your desired AMI ID
      
