AWSTemplateFormatVersion: '2010-09-09'
Description: A template to launch four EC2 instances.

Resources:
  EC2Instance1:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0ae8f15ae66fe8cda'
      KeyName: 'Ansible.key'  # Replace with your key pair name
      Tags:
        - Key: Name
          Value: 'EC2Instance1'

  EC2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0ae8f15ae66fe8cda'
      KeyName: 'Ansible.key'  # Replace with your key pair name
      Tags:
        - Key: Name
          Value: 'EC2Instance2'

  EC2Instance3:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0ae8f15ae66fe8cda'
      KeyName: 'Ansible.key'  # Replace with your key pair name
      Tags:
        - Key: Name
          Value: 'EC2Instance3'

  EC2Instance4:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: 'ami-0ae8f15ae66fe8cda'
      KeyName: 'Ansible.key'  # Replace with your key pair name
      Tags:
        - Key: Name
          Value: 'EC2Instance4'

Outputs:
  Instance1ID:
    Description: 'Instance ID of the first EC2 instance'
    Value: !Ref EC2Instance1

  Instance2ID:
    Description: 'Instance ID of the second EC2 instance'
    Value: !Ref EC2Instance2

  Instance3ID:
    Description: 'Instance ID of the third EC2 instance'
    Value: !Ref EC2Instance3

  Instance4ID:
    Description: 'Instance ID of the fourth EC2 instance'
    Value: !Ref EC2Instance4
